name: CI pipeline

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  typecheck:
    name: Typecheck
    uses: ./.github/workflows/typecheck.yml

  test:
    name: Test
    uses: ./.github/workflows/test.yml
