on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          corepack enable
          yarn install

      - name: Lint
        run: yarn coko-lint run

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build server
        id: build_server
        run: docker compose build

      - name: Test server
        id: test_server
        run: docker compose run server yarn test --colors
