name: Pull request pipeline

on:
  pull_request:

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  typecheck:
    name: Typecheck
    uses: ./.github/workflows/typecheck.yml

  test:
    name: Test
    uses: ./.github/workflows/test.yml
